---
- name: ESXi Pre-Patching Checks
  hosts: all
  gather_facts: no
  vars:
    ansible_user: "{{ esxi_username | default('root') }}"
    ansible_password: "{{ esxi_password | default('Ajay@426344') }}"
    ansible_connection: ssh
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  
  tasks:
    - name: Test SSH connectivity
      raw: echo "SSH_OK"
      register: ssh_test
      failed_when: ssh_test.stdout != "SSH_OK"
      
    - name: Get ESXi version
      raw: vmware -v
      register: esxi_version

    - name: Check datastore free space
      raw: |
        df -h | grep vmfs | head -1
      register: datastore_info

    - name: Parse datastore free space
      raw: |
        df -h | grep vmfs | head -1 | awk '{print $4}' | sed 's/G//'
      register: free_space_gb

    - name: Check for running VMs
      raw: vim-cmd vmsvc/getallvms | grep -v "^Vmid" | wc -l
      register: vm_count

    - name: Get hostname
      raw: hostname
      register: hostname_info

    - name: Display pre-check results
      debug:
        msg:
          - "Hostname: {{ hostname_info.stdout | trim }}"
          - "ESXi Version: {{ esxi_version.stdout | trim }}"
          - "Datastore Info: {{ datastore_info.stdout | trim }}"
          - "Free Space: {{ free_space_gb.stdout | trim }}GB"
          - "Running VMs: {{ vm_count.stdout | trim }}"

    - name: Validate sufficient datastore space (need >2GB)
      fail:
        msg: "Insufficient datastore space: {{ free_space_gb.stdout | trim }}GB (need >2GB)"
      when: 
        - free_space_gb.stdout is defined
        - free_space_gb.stdout | trim | float < 2.0
